//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS3DumpChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PS3DumpChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By using this software you understand that the author (Swizzy) is in no way responsible for ANY damage caused to your console...
        ///
        ///You also acknowledge that you understand that this tool is not a 100% validation of your dumps, it&apos;s only meant to make it easier to check wether or not it&apos;s worth looking closer at or not...
        ///
        ///Did you read these terms/conditions?.
        /// </summary>
        internal static string AcceptTermsMessage {
            get {
                return ResourceManager.GetString("AcceptTermsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By using this software you understand that the author (Swizzy) is in no way responsible for ANY damage caused to your console...
        ///
        ///You also acknowledge that you understand that this tool is not a 100% validation of your dumps, it&apos;s only meant to make it easier to check wether or not it&apos;s worth looking closer at or not...
        ///
        ///Did you skip reading these terms/conditions?.
        /// </summary>
        internal static string AcceptTermsMessageReversed {
            get {
                return ResourceManager.GetString("AcceptTermsMessageReversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can you read?.
        /// </summary>
        internal static string AcceptTermsTitle {
            get {
                return ResourceManager.GetString("AcceptTermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are already using the latest cfg!.
        /// </summary>
        internal static string AlreadyUsingLatestCFG {
            get {
                return ResourceManager.GetString("AlreadyUsingLatestCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are already using the latest hashlist!.
        /// </summary>
        internal static string AlreadyUsingLatestHashlist {
            get {
                return ResourceManager.GetString("AlreadyUsingLatestHashlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Patch Image?.
        /// </summary>
        internal static string autopatch {
            get {
                return ResourceManager.GetString("autopatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to patch this image?.
        /// </summary>
        internal static string autopatchmsg {
            get {
                return ResourceManager.GetString("autopatchmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Something went wrong during the download, try again!.
        /// </summary>
        internal static string baddwl {
            get {
                return ResourceManager.GetString("baddwl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ERROR: Filesize don&apos;t match expected size from the configuration! Please doublecheck your image and configuration!.
        /// </summary>
        internal static string badsize {
            get {
                return ResourceManager.GetString("badsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finished grabbing changelog....
        /// </summary>
        internal static string changelogdone {
            get {
                return ResourceManager.GetString("changelogdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ERROR - Bad dump.
        /// </summary>
        internal static string Checks_StartCheck_ERROR___Bad_dump {
            get {
                return ResourceManager.GetString("Checks_StartCheck_ERROR___Bad_dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuration files|*.cfg|All Files|*.*.
        /// </summary>
        internal static string conf_filter {
            get {
                return ResourceManager.GetString("conf_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на crash.log.
        /// </summary>
        internal static string CrashLogName {
            get {
                return ResourceManager.GetString("CrashLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok... You can&apos;t read can you? well then... better luck next time!.
        /// </summary>
        internal static string DisclaimerFailedMessage {
            get {
                return ResourceManager.GetString("DisclaimerFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading latest PS3 Dump Checker.
        /// </summary>
        internal static string dlingapp {
            get {
                return ResourceManager.GetString("dlingapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading latest hashlist....
        /// </summary>
        internal static string dlinghashlist {
            get {
                return ResourceManager.GetString("dlinghashlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading latest CFG.
        /// </summary>
        internal static string dlinglatestcfg {
            get {
                return ResourceManager.GetString("dlinglatestcfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading changelog....
        /// </summary>
        internal static string downloadchangelog {
            get {
                return ResourceManager.GetString("downloadchangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download completed....
        /// </summary>
        internal static string downloadcompleted {
            get {
                return ResourceManager.GetString("downloadcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ERROR.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ERROR - Bad Size.
        /// </summary>
        internal static string error_bad_size {
            get {
                return ResourceManager.GetString("error_bad_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ERROR: No configuration loaded!.
        /// </summary>
        internal static string error_noconfig {
            get {
                return ResourceManager.GetString("error_noconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ERROR - No config!.
        /// </summary>
        internal static string error_noconfig_title {
            get {
                return ResourceManager.GetString("error_noconfig_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There was an error while downloading the changelog... try again later....
        /// </summary>
        internal static string ErrorDownloadingChangelog {
            get {
                return ResourceManager.GetString("ErrorDownloadingChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There was an error while downloading the update... Try again later!.
        /// </summary>
        internal static string ErrorDownloadingUpdate {
            get {
                return ResourceManager.GetString("ErrorDownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ERROR : you must select a custom ROS patch file or uncheck the option.
        /// </summary>
        internal static string ErrorNoSeletedPatch {
            get {
                return ResourceManager.GetString("ErrorNoSeletedPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There was an error while checking for updates... try again later!.
        /// </summary>
        internal static string ErrorWhileCheckingForUpdates {
            get {
                return ResourceManager.GetString("ErrorWhileCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hashlists |*.hashlist|All Files|*.*.
        /// </summary>
        internal static string hashlist_filter {
            get {
                return ResourceManager.GetString("hashlist_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HTTP ERROR.
        /// </summary>
        internal static string httperror {
            get {
                return ResourceManager.GetString("httperror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are already running the latest version, or the online version haven&apos;t been updated properly....
        /// </summary>
        internal static string LatestVersionRunningOrNotUpdatedOnline {
            get {
                return ResourceManager.GetString("LatestVersionRunningOrNotUpdatedOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maj {
            get {
                object obj = ResourceManager.GetObject("maj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на N/A.
        /// </summary>
        internal static string N_A {
            get {
                return ResourceManager.GetString("N_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No file.
        /// </summary>
        internal static string NoFile {
            get {
                return ResourceManager.GetString("NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hex Files|*.hex|Binary Files|*.bin|All Files|*.*.
        /// </summary>
        internal static string ofdfilter {
            get {
                return ResourceManager.GetString("ofdfilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Woops, online version is bad! :&apos;(.
        /// </summary>
        internal static string OnlineVersionIsBad {
            get {
                return ResourceManager.GetString("OnlineVersionIsBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ERROR: Unable to patch {0} can&apos;t find: {1}.
        /// </summary>
        internal static string PatchFailedCantFindPatchFile {
            get {
                return ResourceManager.GetString("PatchFailedCantFindPatchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please send{0}{1}{0}To Swizzy@xeupd.com!.
        /// </summary>
        internal static string PleaseSendLogTo {
            get {
                return ResourceManager.GetString("PleaseSendLogTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Done! 
        ///The application will restart to apply changes..
        /// </summary>
        internal static string RestartMessage {
            get {
                return ResourceManager.GetString("RestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to restore all settings to default values?.
        /// </summary>
        internal static string RestoreDefaultSettings {
            get {
                return ResourceManager.GetString("RestoreDefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Dump to check.
        /// </summary>
        internal static string seldump {
            get {
                return ResourceManager.GetString("seldump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select configuration file to load.
        /// </summary>
        internal static string select_conf {
            get {
                return ResourceManager.GetString("select_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a patch file.
        /// </summary>
        internal static string selpatch {
            get {
                return ResourceManager.GetString("selpatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use embedded patches.
        /// </summary>
        internal static string UseEmbeddedPatches {
            get {
                return ResourceManager.GetString("UseEmbeddedPatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use internal patcher.
        /// </summary>
        internal static string UseInternalPatcher {
            get {
                return ResourceManager.GetString("UseInternalPatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WARNING!.
        /// </summary>
        internal static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !! WARNING !!
        ///Image has failed verification (A.K.A. it&apos;s probably BAD)! 
        ///Do you really want to patch this image?.
        /// </summary>
        internal static string warningforcepatch {
            get {
                return ResourceManager.GetString("warningforcepatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You&apos;ve found a bug!.
        /// </summary>
        internal static string YouFoundABug {
            get {
                return ResourceManager.GetString("YouFoundABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have been warned....
        /// </summary>
        internal static string YouveBeenWarned {
            get {
                return ResourceManager.GetString("YouveBeenWarned", resourceCulture);
            }
        }
    }
}
